services:
  web:
    build: .
    container_name: cot_site_web
    restart: unless-stopped
    volumes:
      - ./static-files:/app/static

  proxy:
    build: ./nginx
    container_name: cot_site_proxy
    restart: unless-stopped
    volumes:
      - ./static-files:/app/static
    ports:
      - "8000:80"
    depends_on:
      - web
